import { BRAND_LOGOS } from './lookbook-logos.js';
import { BRANDS } from './lookbook-data.js';
const e = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const industries = {'design-system':'디자인 시스템',productivity:'생산성','dev-tools':'개발 도구',fintech:'금융',ecommerce:'커머스',enterprise:'기업','creative-tools':'창작 도구',consumer:'생활',food:'음식',marketing:'마케팅',mobility:'이동·여행',ai:'AI',media:'미디어',social:'소셜',infra:'인프라',lifestyle:'라이프스타일',gaming:'게임',telecom:'통신',manufacturing:'제조',public:'공공',recruitment:'채용',sports:'스포츠'};
const regions={korea:'한국',asia:'아시아',western:'서구권'};
const colors={red:'빨강',orange:'주황',yellow:'노랑',green:'초록',teal:'청록',blue:'파랑',purple:'보라',pink:'분홍',black:'검정',gray:'회색',white:'흰색'};
const state={q:'',industry:'',region:'',color:'',theme:'',sort:'curated',limit:24};
const featured=['anthropic','nvidia','29cm','airbnb','ant-design','amorepacific','airtable','adot'];
const tools=[['Prompt Motion','prompt-motion.com'],['Shotreel','shotreel.app'],['Evil Buttons','evilbuttons.com'],['Drawably','drawably.dev'],['Alcove','tryalcove.com'],['AppLlama','appllama.io'],['Design Bookmark','designbookmark.com'],['Amicons','amicons.design'],['Graphical UI','graphicalui.com']];
function config(b){const dark=b.theme_modes.length===1&&b.theme_modes[0]==='dark'; const editorial=['serif','mixed'].includes(b.font_category);return {dark,editorial,bg:dark?'#17191e':editorial?'#f5f1e9':'#f6f7fa',ink:dark?'#ffffff':'#20242b',accent:/^#[0-9a-f]{6}$/i.test(b.primary_color_hex)?b.primary_color_hex:'#3366ff',font:editorial?'Georgia, serif':'Arial, sans-serif'};}
function brandLogo(b,place=''){const asset=BRAND_LOGOS[b.slug];return asset?`<span class="lb-logo ${place} ${asset.kind}" data-brand="${e(b.slug)}"><img src="assets/brand-logos/${e(asset.file)}" alt="${e(b.brand)} 로고" loading="lazy" decoding="async"></span>`:'';}
function preview(b,large=false){const c=config(b);const kind=b.industry.some(x=>['ecommerce','lifestyle','food'].includes(x))?'shop':b.industry.some(x=>['media','gaming'].includes(x))?'media':'workspace';return `<div class="lb-preview ${kind} ${large?'large':''}" style="--brand:${c.accent};--canvas:${c.bg};--ink:${c.ink};--brand-font:${c.font}"><div class="lb-mini-nav"><div class="lb-brand-lockup">${brandLogo(b)}<b>${e(b.brand)}</b></div><span>Discover &nbsp; Studio &nbsp; ●</span></div><div class="lb-preview-body"><div class="lb-demo-copy"><small>BUILDERS COLLECTION / ${e(regions[b.region])}</small><strong>${kind==='shop'?'Everyday,\nbeautifully.':kind==='media'?'A new way\nto explore.':'Ideas into\npossibilities.'}</strong><p>${e(industries[b.industry[0]]||'디자인')}를 위한 새로운 시선</p><span class="lb-demo-cta">Explore collection ↗</span></div><div class="lb-art" aria-hidden="true"><i></i><i></i><i></i></div></div><div class="lb-mini-bottom"><span>01 — Inspiration</span><span>Made for your next idea</span></div></div>`;}
function guide(b){const c=config(b);return `# ${b.brand} · Builders Lounge 스타일 실험\n\n공개 브랜드 정보를 바탕으로 만든 독립적인 디자인 제안이며 공식 가이드가 아닙니다.\n\n대표 색상: ${c.accent}\n제안 배경: ${c.bg}\n제안 본문색: ${c.ink}\n예시 글꼴: ${c.font} (브랜드 공식 서체 아님)\n\n레이아웃: 중앙 콘텐츠, 넉넉한 여백, 명확한 제목과 하나의 주요 행동 버튼.\n간격: 8 / 16 / 24 / 32 / 48px\n모서리: 12px\n브랜드 로고나 문구를 그대로 재현하지 않고 위 색상과 분위기를 활용한 독창적인 화면을 만들어 주세요.\n모바일에서는 한 열로 배치하고 키보드 탐색과 충분한 글자 대비를 확보해 주세요.\n\n:root { --accent: ${c.accent}; --surface: ${c.bg}; --text: ${c.ink}; --radius: 12px; }\n`;}
async function copy(value,button){try{await navigator.clipboard.writeText(value);button.textContent='복사 완료';}catch{button.textContent='복사할 수 없습니다';}}
function detail(root,b){const c=config(b);root.innerHTML=`<section class="lb"><a class="lb-back" href="#lookbook">← 전체 브랜드 보기</a><div class="lb-detail-heading">${brandLogo(b,'detail-logo')}<div><p class="eyebrow">BRAND STUDY</p><h1>${e(b.brand)}</h1><p>${e(b.brand_ko)} · ${regions[b.region]} · ${b.industry.map(x=>industries[x]||x).join(' / ')}</p></div><span class="lb-badge">${b.theme_modes.join(' / ')}</span></div>${preview(b,true)}<p class="lb-note">브랜드의 공개 색상 정보를 활용해 새로 제작한 예시입니다. 공식 웹사이트·디자인 가이드가 아닙니다.</p><div class="lb-tabs" role="tablist" aria-label="브랜드 상세"><button role="tab" aria-selected="true" data-tab="palette">색상·서체</button><button role="tab" aria-selected="false" data-tab="components">UI 구성</button><button role="tab" aria-selected="false" data-tab="guide">내 프로젝트에 적용</button></div><div class="lb-panel" role="tabpanel" tabindex="0"></div></section>`;
const panel=root.querySelector('.lb-panel');
function tab(name){root.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',String(x.dataset.tab===name)));if(name==='palette'){panel.innerHTML=`<h2>컬러 팔레트</h2><p>대표 색상과 함께 쓰기 좋은 배경·본문색 제안입니다.</p><div class="lb-swatches">${[[c.accent,'대표 색상'],[c.bg,'배경 제안'],[c.ink,'본문 제안']].map(([hex,label])=>`<button data-color="${hex}"><i style="background:${hex}"></i><b>${label}</b><span>${hex} · 복사</span></button>`).join('')}</div><h2>타이포그래피 제안</h2><p class="lb-type" style="font-family:${c.font}">Build something meaningful.<br>아이디어가 시작되는 공간</p><p>${e(c.font)} · 화면 예시용 대체 서체</p>`;panel.querySelectorAll('[data-color]').forEach(x=>x.onclick=()=>copy(x.dataset.color,x.querySelector('span')));}else if(name==='components'){panel.innerHTML=`<h2>프로젝트용 UI 샘플</h2><p>8px 단위 간격과 12px 모서리를 기본으로 구성했습니다.</p><div class="lb-component-sample" style="--brand:${c.accent}"><button class="lb-sample-primary">주요 작업</button><button class="lb-sample-secondary">보조 작업</button><label>프로젝트 이름<input placeholder="새로운 아이디어"></label><div class="lb-sample-card"><small>YOUR NEXT PROJECT</small><h3>작은 아이디어의 큰 가능성</h3><p>제목, 설명, 행동을 명확하게 구분해 보세요.</p></div><p role="status" data-sample-status></p></div>`;panel.querySelectorAll('button').forEach(x=>x.onclick=()=>{panel.querySelector('[data-sample-status]').textContent='버튼의 선택 상태를 확인했습니다. 실제 서비스 작업은 연결되지 않은 예시입니다.';});}else{panel.innerHTML=`<h2>내 프로젝트의 출발점으로</h2><p>선택한 색상과 레이아웃 제안을 AI에게 전달하거나 파일로 보관하세요.</p><div class="lb-actions"><button data-copy-guide>디자인 프롬프트 복사</button><button data-download>스타일 가이드 다운로드 ↓</button></div><pre>${e(guide(b))}</pre>`;panel.querySelector('[data-copy-guide]').onclick=event=>copy(guide(b),event.currentTarget);panel.querySelector('[data-download]').onclick=()=>{const url=URL.createObjectURL(new Blob([guide(b)],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=b.slug+'-builders-style.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}}
root.querySelectorAll('[data-tab]').forEach(x=>{x.onclick=()=>tab(x.dataset.tab);x.onkeydown=event=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const tabs=[...root.querySelectorAll('[data-tab]')];const next=tabs[(tabs.indexOf(x)+(event.key==='ArrowRight'?1:2))%3];next.focus();tab(next.dataset.tab);};});tab('palette');}
export function renderLookbook(root,id){if(id){const b=BRANDS.find(x=>x.slug===id);if(b)return detail(root,b);root.innerHTML='<section class="lb"><h1>브랜드를 찾을 수 없습니다</h1><a href="#lookbook">전체 브랜드 보기</a></section>';return;}
const select=(key,label,options)=>`<label>${label}<select aria-label="${label}" data-filter="${key}"><option value="">전체</option>${Object.entries(options).map(([v,l])=>`<option value="${v}" ${state[key]===v?'selected':''}>${l}</option>`).join('')}</select></label>`;
root.innerHTML=`<section class="lb"><header class="lb-heading"><p class="eyebrow">BUILDERS DESIGN LIBRARY</p><h1>브랜드 룩북<span>${BRANDS.length}</span></h1><p>좋아하는 브랜드에서, 나만의 디자인으로.<br>색과 서체, 화면의 분위기를 한곳에서 탐색하세요.</p></header><div class="lb-search"><span aria-hidden="true">⌕</span><input type="search" aria-label="브랜드 검색" placeholder="브랜드 이름 검색 · 예: 애플, NVIDIA, 이솝" value="${e(state.q)}"></div><div class="lb-filters">${select('industry','업종',industries)}${select('region','지역',regions)}${select('color','색상',colors)}${select('theme','테마',{light:'라이트',dark:'다크'})}<button data-reset>초기화</button></div><div class="lb-result-bar"><span data-count role="status"></span><label>정렬 <select data-sort><option value="curated" ${state.sort==='curated'?'selected':''}>추천순</option><option value="name" ${state.sort==='name'?'selected':''}>이름순</option></select></label></div><div class="lb-grid"></div><button class="lb-more" data-more>브랜드 더 보기</button><p class="lb-note">공개 브랜드 목록·대표 색상 참고: 오빠두엑셀 디자인 시스템. 미리보기와 UI 제안은 빌더스 라운지가 독립적으로 제작했습니다.</p><details class="lb-tools"><summary>디자이너들을 위한 웹사이트 · 9</summary><div>${tools.map(([name,url])=>`<a href="https://${url}" target="_blank" rel="noopener noreferrer">${name} ↗</a>`).join('')}</div></details></section>`;
function results(){const q=state.q.trim().toLowerCase();const list=BRANDS.filter(b=>(!q||(b.brand+' '+b.brand_ko).toLowerCase().includes(q))&&(!state.industry||b.industry.includes(state.industry))&&(!state.region||b.region===state.region)&&(!state.color||b.color_family===state.color)&&(!state.theme||b.theme_modes.includes(state.theme))).sort((a,b)=>state.sort==='name'?a.brand.localeCompare(b.brand):((featured.indexOf(a.slug)+1||999)-(featured.indexOf(b.slug)+1||999)||a.brand.localeCompare(b.brand)));root.querySelector('[data-count]').textContent=`${list.length}개 브랜드 · ${Math.min(list.length,state.limit)}개 표시`;root.querySelector('.lb-grid').innerHTML=list.length?list.slice(0,state.limit).map(b=>`<a class="lb-card" href="#lookbook/${e(b.slug)}" aria-label="${e(b.brand)} 상세 보기">${preview(b)}<div class="lb-card-meta">${brandLogo(b,'meta-logo')}<div><h2>${e(b.brand)}</h2><p>${e(b.brand_ko)} · ${regions[b.region]}</p></div><span class="lb-color-dot" style="background:${config(b).accent}"></span></div><div class="lb-tags">${b.industry.slice(0,2).map(x=>`<span>${industries[x]||e(x)}</span>`).join('')}<span>상세 보기 ↗</span></div></a>`).join(''):'<div class="lb-empty"><h2>검색 결과가 없습니다</h2><p>다른 브랜드 이름을 입력하거나 필터를 초기화해 주세요.</p></div>';root.querySelector('[data-more]').hidden=list.length<=state.limit;}
root.querySelector('input').oninput=event=>{state.q=event.target.value;state.limit=24;results();};root.querySelectorAll('[data-filter]').forEach(x=>x.onchange=()=>{state[x.dataset.filter]=x.value;state.limit=24;results();});root.querySelector('[data-sort]').onchange=event=>{state.sort=event.target.value;results();};root.querySelector('[data-reset]').onclick=()=>{Object.assign(state,{q:'',industry:'',region:'',color:'',theme:'',limit:24});renderLookbook(root);};root.querySelector('[data-more]').onclick=()=>{state.limit+=24;results();};results();}
