const PUBLISHED = "published";

const prompts = [
  {
    id: "prompt-stic",
    cover: "assets/og.png",
    kicker: "업무",
    type: "prompt",
    title: "STIC 요청 템플릿",
    summary: "상황·과업·의도·제약을 빠르게 정리해 원하는 답의 방향을 맞춥니다.",
    tags: ["업무", "기획", "기초"],
    category: "업무",
    useCase: "AI에게 일을 맡기기 전에 요구사항을 구조화할 때",
    expected: "모호한 요청이 실행 가능한 작업 지시서로 정리됩니다.",
    copyText: "Situation: 현재 상황을 설명합니다.\nTask: AI가 해야 할 일을 한 문장으로 씁니다.\nIntent: 이 결과가 필요한 이유를 적습니다.\nConstraints: 형식, 분량, 금지사항을 적습니다.\n\n위 내용을 바탕으로 먼저 이해한 내용을 요약하고, 모호한 점이 있으면 질문한 뒤 작업을 시작해 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "AI Builders Lab 공개 가이드",
    sourceUrl: "https://builderslab.ai-hub-os.com/",
    featured: true,
    status: PUBLISHED,
  },
  {
    id: "prompt-report-mode",
    cover: "assets/report-hub-banner.png",
    kicker: "글쓰기",
    type: "prompt",
    title: "Report Mode 리서치 정리",
    summary: "자료를 사실·해석·전망·리스크로 나누어 읽기 쉬운 보고서로 구성합니다.",
    tags: ["글쓰기", "리서치", "보고서"],
    category: "글쓰기",
    useCase: "여러 출처의 정보를 임원용 브리핑으로 정리할 때",
    expected: "근거와 의견이 섞이지 않은 짧은 리포트가 만들어집니다.",
    copyText: "아래 자료를 바탕으로 한국어 브리핑을 작성해 주세요.\n- 결론: 먼저 한 문장으로 답합니다.\n- 사실: 출처가 직접 확인되는 내용만 씁니다.\n- 분석: 사실에서 도출한 해석을 분리합니다.\n- 전망: 가능성을 조건과 함께 씁니다.\n- 리스크: 확인이 필요한 점과 반대 시나리오를 적습니다.\n\n각 핵심 주장 뒤에 출처 링크를 붙이고, 확인할 수 없는 내용은 추정으로 표시해 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "Report Hub",
    sourceUrl: "https://aireport.ai-hub-os.com/",
    featured: true,
    status: PUBLISHED,
  },
  {
    id: "prompt-image",
    cover: "assets/hero-builders-character-poster.jpg",
    kicker: "이미지",
    type: "prompt",
    title: "이미지 생성 기본 프레임",
    summary: "주제·구도·조명·재질·금지사항을 한 번에 지정하는 이미지 프롬프트입니다.",
    tags: ["이미지", "창작"],
    category: "이미지",
    useCase: "원하는 결과를 반복해서 재현하고 싶을 때",
    expected: "생성 모델이 이해하기 쉬운 시각적 지시문이 됩니다.",
    copyText: "주제: [무엇을 그릴지]\n장면: [어디에서 무엇을 하는지]\n구도: [카메라 위치와 화면 비율]\n스타일: [질감·시대·매체]\n빛과 색: [광원·색상·분위기]\n디테일: [반드시 보여야 할 요소]\n제외: [원하지 않는 요소]\n\n위 내용을 자연스러운 한 문단의 이미지 생성 프롬프트로 변환해 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "AI Builders Lab 프롬프트 모음",
    sourceUrl: "https://builderslab.ai-hub-os.com/",
    status: PUBLISHED,
  },
  {
    id: "prompt-handdrawn",
    cover: "assets/hero-builders-character-poster.jpg",
    kicker: "이미지",
    type: "prompt",
    title: "손그림 변환",
    summary: "디지털 이미지를 따뜻한 손그림 느낌으로 바꾸되 핵심 형태는 보존합니다.",
    tags: ["이미지", "스타일"],
    category: "이미지",
    useCase: "사진이나 스크린샷을 콘텐츠용 일러스트로 바꿀 때",
    expected: "원본의 정보는 유지하고 선과 색감만 손그림처럼 바꿉니다.",
    copyText: "원본 이미지의 인물·사물·배치와 핵심 특징은 유지해 주세요. 가볍게 흔들리는 연필 선, 종이의 미세한 결, 제한된 색상 팔레트, 손으로 칠한 듯한 불균일한 채색을 적용해 주세요. 과도한 디테일과 사진처럼 반짝이는 질감은 제외해 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "공감툰 제작 실험",
    sourceUrl: "https://aihubos.github.io/gonggamtoon/",
    status: PUBLISHED,
  },
  {
    id: "prompt-caricature",
    type: "prompt",
    title: "캐리커처 한 장",
    summary: "인물의 인상적인 특징을 과장해 유쾌한 프로필 카드로 만듭니다.",
    tags: ["이미지", "캐릭터"],
    category: "이미지",
    useCase: "소개 페이지나 커뮤니티 프로필 이미지를 만들 때",
    expected: "닮은 느낌과 유머를 함께 가진 캐릭터가 완성됩니다.",
    copyText: "인물의 알아볼 수 있는 특징 2~3개를 유지하고, 표정과 소품을 한 가지씩 과장한 친근한 캐리커처를 만들어 주세요. 배경은 단순한 단색, 선은 깨끗한 마커 느낌, 얼굴은 과도하게 왜곡하지 않습니다. 작은 썸네일에서도 표정이 읽히도록 대비를 높여 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "AI Builders Lab 프롬프트 모음",
    sourceUrl: "https://builderslab.ai-hub-os.com/",
    status: PUBLISHED,
  },
  {
    id: "prompt-small-drawing",
    type: "prompt",
    title: "하찮은 그림의 힘",
    summary: "완벽함 대신 단순한 선과 한 문장으로 기억에 남는 이미지를 만듭니다.",
    tags: ["이미지", "이미지 게시판", "창작"],
    category: "이미지",
    useCase: "빠른 공감 카드나 이미지 게시판 콘텐츠를 만들 때",
    expected: "작은 화면에서도 메시지가 먼저 보이는 결과가 됩니다.",
    copyText: "주제는 [한 문장]으로 제한합니다. 삐뚤빼뚤한 검은 선 3~5개와 단순한 표정만 사용해 주세요. 배경은 흰색 또는 아주 옅은 색, 글자는 한글 12자 이내로 크게 배치합니다. 예쁘게 꾸미기보다 ‘아, 이 마음 알지’라는 반응이 먼저 나오게 해 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "빌더들의 이미지 게시판 제작 규칙",
    sourceUrl: "https://aihubos.github.io/builders-lounge/",
    status: PUBLISHED,
  },
  {
    id: "prompt-blog-style",
    type: "prompt",
    title: "제레미 블로그 문체",
    summary: "핵심 결론을 앞에 두고, 실행 경험과 다음 행동을 담은 글로 고칩니다.",
    tags: ["글쓰기", "블로그"],
    category: "글쓰기",
    useCase: "AI 도구를 직접 써본 경험을 읽기 쉬운 글로 남길 때",
    expected: "짧은 문장과 구체적인 사례가 있는 실전형 글이 됩니다.",
    copyText: "아래 초안을 ‘결론 → 직접 해본 일 → 실제 확인 결과 → 막힌 점 → 다음 행동’ 순서로 다시 써 주세요. 전문용어는 바로 풀어 쓰고, 추상적인 감탄보다 숫자·화면·실패 사례를 우선합니다. 독자가 오늘 바로 따라 할 수 있는 한 가지 행동으로 끝내 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "콘텐츠 연재 자산화 시스템",
    sourceUrl: "https://blog.naver.com/jeremylee0213",
    status: PUBLISHED,
  },
  {
    id: "prompt-video-plan",
    type: "prompt",
    title: "영상 기획 5문장",
    summary: "누구에게 어떤 변화를 줄지부터 정해 짧은 영상의 뼈대를 만듭니다.",
    tags: ["영상", "기획"],
    category: "영상",
    useCase: "AI 도구 소개나 튜토리얼 영상을 빠르게 기획할 때",
    expected: "첫 장면부터 마무리 CTA까지 흐름이 끊기지 않습니다.",
    copyText: "다음 다섯 문장을 먼저 써 주세요.\n1. 이 영상이 필요한 사람\n2. 시작 3초에 던질 문제\n3. 직접 보여줄 화면 또는 행동\n4. 시청자가 얻는 변화\n5. 다음에 할 행동\n\n각 문장을 한 컷으로 바꾸고, 컷마다 화면·내레이션·자막을 나눠 표로 정리해 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "ShortHub 제작 흐름",
    sourceUrl: "https://aihubos.github.io/shorthub/",
    status: PUBLISHED,
  },
  {
    id: "prompt-ai-coding",
    type: "prompt",
    title: "AI 코딩 작업 지시",
    summary: "코드 수정 범위와 확인 방법을 함께 적어 AI가 안전하게 작은 변경을 하게 합니다.",
    tags: ["자동화", "코딩"],
    category: "자동화",
    useCase: "기존 프로젝트에 기능을 추가하거나 버그를 고칠 때",
    expected: "변경 파일·완료 기준·검증 결과가 한 번에 남습니다.",
    copyText: "목표: [한 문장]\n수정 범위: [허용 파일과 금지 파일]\n현재 문제: [재현 방법]\n완료 기준: [사용자가 확인할 화면]\n확인 방법: [실행할 명령]\n\n먼저 현재 파일과 변경사항을 요약하고, 작은 단계로 구현한 뒤 각 단계의 확인 결과를 한국어로 보고해 주세요. 비밀값은 절대 출력하지 마세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "Codex 작업 가이드",
    sourceUrl: "https://github.com/aihubos/builders-lounge",
    status: PUBLISHED,
  },
  {
    id: "prompt-translation",
    type: "prompt",
    title: "업무 번역 검토",
    summary: "직역보다 목적과 독자를 우선해 자연스러운 업무 문장으로 번역합니다.",
    tags: ["업무", "글쓰기", "학습"],
    category: "학습",
    useCase: "외국어 자료를 팀이 바로 사용할 수 있는 문서로 바꿀 때",
    expected: "원문의 의미·뉘앙스·용어가 검토 가능한 형태로 남습니다.",
    copyText: "다음 문장을 한국어 업무 문서로 번역해 주세요. 원문 의미를 훼손하지 않되 한국 독자가 자연스럽게 읽도록 다듬습니다. 고유명사와 기술 용어는 원문을 괄호로 병기하고, 모호한 표현은 ‘번역 메모’로 따로 표시해 주세요. 마지막에 핵심 용어 5개와 권장 번역을 표로 정리해 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "LLM Wiki 학습 자료",
    sourceUrl: "https://github.com/aihubos/llmwiki",
    status: PUBLISHED,
  },
  {
    id: "prompt-openclaw-slack",
    type: "prompt",
    title: "OpenClaw·Slack 자동화 점검",
    summary: "알림 자동화를 만들 때 권한·실패·사람 확인 지점을 먼저 정합니다.",
    tags: ["자동화", "에이전트", "운영"],
    category: "자동화",
    useCase: "팀 메신저와 에이전트를 연결하는 흐름을 설계할 때",
    expected: "자동화가 실행되더라도 사람이 마지막으로 확인할 지점이 분명해집니다.",
    copyText: "다음 자동화 아이디어를 검토해 주세요.\n1. 트리거와 필요한 권한\n2. 입력 데이터와 개인정보 위험\n3. 성공·실패·재시도 조건\n4. Slack에 보낼 메시지 예시\n5. 사람이 승인해야 하는 단계\n\n실제로 실행하거나 비밀값을 요청하지 말고, 먼저 안전한 설계와 테스트 체크리스트만 작성해 주세요.",
    author: "AI Builders Lab 운영팀",
    sourceLabel: "OpenClaw 운영 자료",
    sourceUrl: "https://github.com/aihubos/openclaw",
    status: PUBLISHED,
  },
];

const newsletters = [
  {
    id: "newsletter-001",
    cover: "assets/hero-builders-wave-poster.jpg",
    kicker: "뉴스레터",
    type: "newsletter",
    title: "AI 빌더스 랩 뉴스레터 1호, AI 에이전트 실전 업무와 보안",
    summary: "AI 에이전트가 데모를 넘어 실제 업무에 들어오는 순간, 성능보다 운영과 보안이 먼저입니다.",
    tags: ["AI 에이전트", "자동화", "보안"],
    issue: "1호",
    publishedAt: "2026-08-20",
    author: "AI Builders Lab",
    sourceLabel: "AI 빌더스 랩 뉴스레터 초안",
    sourceUrl: "https://aihubos.github.io/builders-lounge/",
    featured: true,
    status: PUBLISHED,
    sections: [
      { heading: "이번 호 핵심 문장", body: "에이전트의 다음 경쟁력은 무엇을 할 수 있는가보다, 무엇을 언제 멈추고 사람이 확인하게 하는가에 달려 있습니다." },
      { heading: "주요 소식", body: "AI 에이전트가 브라우저·코드·업무 도구를 직접 다루는 사례가 늘고 있습니다. 동시에 권한 범위, 로그 보존, 잘못된 자동 실행을 막는 승인 단계가 제품 설계의 중심으로 이동했습니다." },
      { heading: "빌더에게 의미하는 점", body: "작은 자동화부터 시작하되, 입력·출력·실패 시 행동을 문서로 남겨야 합니다. ‘작동한다’는 확인과 ‘운영해도 안전하다’는 확인을 분리해 보세요." },
      { heading: "이번 주 직접 해볼 일", body: "반복 업무 하나를 골라 STIC 형식으로 적고, 자동 실행 대신 먼저 초안만 생성하는 검토 모드를 만들어 보세요." },
      { heading: "다음 호 예고", body: "혼자 만든 도구를 팀이 다시 사용할 수 있게 만드는 공개 문서와 운영 루틴을 다룹니다." },
    ],
  },
  {
    id: "newsletter-special-agents",
    cover: "assets/og.png",
    kicker: "뉴스레터",
    type: "newsletter",
    title: "AI 빌더스 랩 뉴스레터 스페셜, AI 에이전트 삼국지",
    summary: "모델·도구·사람의 역할을 나누어 보면 에이전트 생태계의 변화가 더 선명해집니다.",
    tags: ["AI 에이전트", "빌더 이야기"],
    issue: "스페셜",
    publishedAt: "2026-08-08",
    author: "AI Builders Lab",
    sourceLabel: "배움의 달인 Newsletter 아카이브 참고",
    sourceUrl: "https://blog.naver.com/jeremylee0213",
    status: PUBLISHED,
    sections: [
      { heading: "이번 호 핵심 문장", body: "좋은 에이전트는 사람을 대신하는 존재가 아니라 사람의 판단이 필요한 순간을 더 잘 드러내는 도구입니다." },
      { heading: "주요 소식", body: "모델의 추론 능력, 작업을 연결하는 도구, 결과를 검증하는 사람이 함께 진화하고 있습니다. 어느 하나만 바꿔도 전체 흐름이 달라집니다." },
      { heading: "빌더에게 의미하는 점", body: "처음부터 거대한 자동화를 만들기보다, 한 번에 한 가지 결과를 내고 사람이 확인하는 작은 루프를 반복하세요." },
      { heading: "이번 주 직접 해볼 일", body: "자주 쓰는 프롬프트 하나를 공개용 템플릿으로 정리하고, 다른 사람이 재현할 수 있는 입력 예시를 붙여 보세요." },
      { heading: "다음 호 예고", body: "콘텐츠를 한 번 만들고 뉴스레터·영상·게시판으로 확장하는 자산화 흐름을 소개합니다." },
    ],
  },
];

const videos = [
  { id: "video-openclaw", type: "video", title: "오픈클로 설치법, 자는 동안 일하는 AI 비서", summary: "처음 시작하는 사람을 위한 OpenClaw 설치와 기본 흐름을 살펴봅니다.", tags: ["AI 에이전트", "입문"], category: "AI 에이전트", videoId: "609DF4SFwQs", duration: "18분", difficulty: "입문", author: "배움의 달인", sourceLabel: "YouTube", sourceUrl: "https://www.youtube.com/watch?v=609DF4SFwQs", status: PUBLISHED },
  { id: "video-chatgpt-agent", type: "video", title: "ChatGPT 에이전트로 나만의 AI 만들기", summary: "코딩을 몰라도 작업 흐름을 설계하는 방법을 보여주는 입문 영상입니다.", tags: ["AI 입문", "에이전트"], category: "AI 입문", videoId: "-jYKUwldgek", duration: "21분", difficulty: "입문", author: "배움의 달인", sourceLabel: "YouTube", sourceUrl: "https://www.youtube.com/watch?v=-jYKUwldgek", status: PUBLISHED },
  { id: "video-veo-capcut", type: "video", title: "Veo와 CapCut으로 짧은 영상 만들기", summary: "아이디어를 세로 영상으로 옮기는 기본 제작 루틴을 정리합니다.", tags: ["영상 제작", "자동화"], category: "이미지·영상 제작", videoId: "1xVON92uhtI", duration: "15분", difficulty: "입문", author: "AI인사이트", sourceLabel: "YouTube", sourceUrl: "https://www.youtube.com/watch?v=1xVON92uhtI", status: PUBLISHED },
  { id: "video-ai-concert", type: "video", title: "인공지능 콘서트, 꿈과 희망의 세계", summary: "AI를 활용한 창작과 이야기의 가능성을 가볍게 만나보는 콘텐츠입니다.", tags: ["빌더 프로젝트", "창작"], category: "빌더 프로젝트", videoId: "k44cjt5y6qc", duration: "32분", difficulty: "모두", author: "배움의 달인", sourceLabel: "YouTube", sourceUrl: "https://www.youtube.com/watch?v=k44cjt5y6qc", status: PUBLISHED },
  { id: "video-ai-membership", type: "video", title: "10명의 AI 직원이 일하는 시스템", summary: "AI 도구를 조직의 반복 업무와 연결할 때 생각할 점을 살펴봅니다.", tags: ["자동화", "조직"], category: "자동화", videoId: "G8MZ9TuFtYU", duration: "24분", difficulty: "중급", author: "배움의 달인", sourceLabel: "YouTube", sourceUrl: "https://www.youtube.com/watch?v=G8MZ9TuFtYU", status: PUBLISHED },
  { id: "video-ai-news-fatigue", type: "video", title: "매일 쏟아지는 AI 뉴스에 흔들리지 않는 법", summary: "정보를 모두 따라가기보다 내 프로젝트에 필요한 것을 고르는 기준을 제안합니다.", tags: ["학습", "빌더 이야기"], category: "AI 입문", videoId: "my9CAJTOrow", duration: "17분", difficulty: "모두", author: "배움의 달인", sourceLabel: "YouTube", sourceUrl: "https://www.youtube.com/watch?v=my9CAJTOrow", status: PUBLISHED },
];

const memes = [
  { id: "meme-ai-01", type: "meme", title: "프롬프트는 완벽했는데", summary: "결과를 보고 다시 STIC부터 쓰는 빌더의 하루", tags: ["AI 공감"], category: "AI 공감", kicker: "AI 공감", cover: "assets/og.png", caption: "프롬프트: 완벽함\n결과: 다시 질문해 주세요", credit: "AI Builders Lab 자체 제작", sourceLabel: "Builders Lounge", sourceUrl: "https://aihubos.github.io/builders-lounge/", tone: "blue", status: PUBLISHED },
  { id: "meme-ai-02", type: "meme", title: "AI가 알아서 해주겠지", summary: "그리고 마지막 승인 버튼 앞에서 멈추는 이유", tags: ["AI 공감"], category: "AI 공감", kicker: "AI 공감", cover: "assets/hero-builders-wave-poster.jpg", caption: "자동화의 마지막 단계\n사람: 이거 진짜 보내도 돼?", credit: "AI Builders Lab 자체 제작", sourceLabel: "Builders Lounge", sourceUrl: "https://aihubos.github.io/builders-lounge/", tone: "navy", status: PUBLISHED },
  { id: "meme-ai-03", type: "meme", title: "모델 업데이트 알림", summary: "방금 익힌 기능을 다시 배워야 하는 순간", tags: ["AI 공감"], category: "AI 공감", kicker: "AI 공감", cover: "assets/hero-builders-character-poster.jpg", caption: "오늘의 계획\n새 모델 비교하기", credit: "AI Builders Lab 자체 제작", sourceLabel: "Builders Lounge", sourceUrl: "https://aihubos.github.io/builders-lounge/", tone: "orange", status: PUBLISHED },
  { id: "meme-dev-01", type: "meme", title: "한 줄만 고치면 돼", summary: "그 한 줄이 파일 열두 개로 번지는 과정", tags: ["개발 공감"], category: "개발 공감", kicker: "개발 공감", cover: "assets/report-hub-banner.png", caption: "변경 범위: 한 줄\n영향 범위: 우주", credit: "AI Builders Lab 자체 제작", sourceLabel: "Builders Lounge", sourceUrl: "https://aihubos.github.io/builders-lounge/", tone: "green", status: PUBLISHED },
  { id: "meme-dev-02", type: "meme", title: "콘솔에 오류가 없어요", summary: "그래서 화면을 직접 눌러보기로 했다", tags: ["개발 공감"], category: "개발 공감", kicker: "개발 공감", cover: "assets/hero-wave-background.png", caption: "npm run check 통과\n사용자: 버튼이 안 눌려요", credit: "AI Builders Lab 자체 제작", sourceLabel: "Builders Lounge", sourceUrl: "https://aihubos.github.io/builders-lounge/", tone: "purple", status: PUBLISHED },
  { id: "meme-dev-03", type: "meme", title: "배포 완료의 기준", summary: "코드가 올라간 것과 실제 페이지가 보이는 것은 다릅니다.", tags: ["개발 공감"], category: "개발 공감", kicker: "개발 공감", cover: "assets/og.png", caption: "배포 성공\n공개 화면: 아직 예전 버전", credit: "AI Builders Lab 자체 제작", sourceLabel: "Builders Lounge", sourceUrl: "https://aihubos.github.io/builders-lounge/", tone: "red", status: PUBLISHED },
  { id: "meme-result-gonggamtoon", type: "meme", title: "공감툰 제작기", summary: "대화 한 줄에서 공감 카드까지 이어지는 원본 앱입니다.", tags: ["빌더 결과물", "웹툰"], category: "빌더 결과물", kicker: "빌더 결과물", caption: "오늘의 감정\n한 컷으로 남겨보기", credit: "공감툰", sourceLabel: "공감툰 원본 앱", sourceUrl: "https://aihubos.github.io/gonggamtoon/", cover: "assets/og.png", tone: "blue", status: PUBLISHED },
  { id: "meme-result-shorthub", type: "meme", title: "ShortHub", summary: "긴 영상을 짧은 콘텐츠로 바꾸는 빌더 프로젝트", tags: ["빌더 결과물", "영상"], category: "빌더 결과물", kicker: "빌더 결과물", caption: "한 편의 영상\n여러 개의 장면", credit: "ShortHub", sourceLabel: "ShortHub 원본 앱", sourceUrl: "https://aihubos.github.io/shorthub/", cover: "assets/hero-builders-wave-poster.jpg", tone: "navy", status: PUBLISHED },
  { id: "meme-result-masterpiece", type: "meme", title: "세계명화 프롬프트", summary: "명화와 캐릭터를 조합해 새로운 장면을 만드는 도구", tags: ["빌더 결과물", "이미지"], category: "빌더 결과물", kicker: "빌더 결과물", caption: "원본은 명화\n결과는 나만의 장면", credit: "World Masterpiece Bot", sourceLabel: "세계명화 프롬프트", sourceUrl: "https://aihubos.github.io/world-masterpiece-bot/", cover: "assets/report-hub-banner.png", tone: "orange", status: PUBLISHED },
  { id: "meme-result-token", type: "meme", title: "토큰 비용 계산기", summary: "모델과 사용량을 바꿔 예상 비용을 비교하는 작은 도구", tags: ["빌더 결과물", "AI 도구"], category: "빌더 결과물", kicker: "빌더 결과물", caption: "좋은 아이디어\n비용까지 알아야 오래 갑니다", credit: "Token Calculator", sourceLabel: "토큰 비용 계산기", sourceUrl: "https://aihubos.github.io/token-calculator/", cover: "assets/og.png", tone: "green", status: PUBLISHED },
  { id: "meme-result-pokopia", type: "meme", title: "포코피아 블록 가든", summary: "가볍게 즐기며 만든 블록 퍼즐 게임", tags: ["빌더 결과물", "게임"], category: "빌더 결과물", kicker: "빌더 결과물", caption: "잠깐만 하려고 했는데\n블록이 한 줄 더 남았어요", credit: "Pokopia Block Garden", sourceLabel: "게임방", sourceUrl: "https://aihubos.github.io/pokopia-tetris/", cover: "assets/hero-wave-background.png", tone: "green", status: PUBLISHED },
  { id: "meme-result-mallang", type: "meme", title: "말랑바다 모험단", summary: "작은 캐릭터와 함께 떠나는 브라우저 모험", tags: ["빌더 결과물", "게임"], category: "빌더 결과물", kicker: "빌더 결과물", caption: "오늘의 퀘스트\n일단 한 번 눌러보기", credit: "말랑바다 모험단", sourceLabel: "게임방", sourceUrl: "https://aihubos.github.io/mallang-sea-adventure/", cover: "assets/hero-builders-character-poster.jpg", tone: "blue", status: PUBLISHED },
];

const games = [
  { id: "game-pokopia", type: "game", title: "포코피아 블록 가든", summary: "블록을 맞추며 잠깐 쉬어가는 퍼즐 게임입니다.", tags: ["퍼즐", "가볍게"], author: "AI Builders Lab", publishedAt: "2026-08-18", sourceLabel: "GitHub Pages", sourceUrl: "https://aihubos.github.io/pokopia-tetris/", launchUrl: "https://aihubos.github.io/pokopia-tetris/", embedAllowed: true, mobileReady: true, controls: "화면 버튼 또는 키보드 방향키", status: PUBLISHED },
  { id: "game-mallang", type: "game", title: "말랑바다 모험단", summary: "말랑한 캐릭터와 바다를 탐험하는 짧은 모험입니다.", tags: ["모험", "캐주얼"], author: "AI Builders Lab", publishedAt: "2026-08-12", sourceLabel: "GitHub Pages", sourceUrl: "https://aihubos.github.io/mallang-sea-adventure/", launchUrl: "https://aihubos.github.io/mallang-sea-adventure/", embedAllowed: true, mobileReady: true, controls: "화면 터치 또는 키보드", status: PUBLISHED },
  { id: "game-seojin", type: "game", title: "서진이의 미로 모험", summary: "출구를 찾으며 집중력을 시험하는 미로 게임입니다.", tags: ["미로", "탐험"], author: "AI Builders Lab", publishedAt: "2026-08-10", sourceLabel: "GitHub Pages", sourceUrl: "https://aihubos.github.io/seojin-maze-adventure/", launchUrl: "https://aihubos.github.io/seojin-maze-adventure/", embedAllowed: true, mobileReady: true, controls: "화면 조작 또는 방향키", status: PUBLISHED },
];

export const COMMUNITY_DATA = Object.freeze({
  prompts: Object.freeze(prompts.map(Object.freeze)),
  newsletters: Object.freeze(newsletters.map(Object.freeze)),
  videos: Object.freeze(videos.map(Object.freeze)),
  memes: Object.freeze(memes.map(Object.freeze)),
  games: Object.freeze(games.map(Object.freeze)),
});

export const COMMUNITY_CATEGORIES = Object.freeze({
  prompts: Object.freeze(["전체", "이미지", "영상", "업무", "글쓰기", "자동화", "학습"]),
  videos: Object.freeze(["전체", "AI 입문", "AI 에이전트", "자동화", "이미지·영상 제작", "빌더 프로젝트"]),
  memes: Object.freeze(["전체", "AI 공감", "개발 공감", "빌더 결과물"]),
});

export function publishedItems(type) {
  return (COMMUNITY_DATA[type] || []).filter((item) => item.status === PUBLISHED);
}

export function getFeaturedPrompts() {
  return publishedItems("prompts").filter((item) => item.featured).slice(0, 3);
}

export function getLatestNewsletter() {
  return publishedItems("newsletters").slice().sort((a, b) => String(b.publishedAt).localeCompare(String(a.publishedAt)))[0] || null;
}
